// This file is generated by SQLBoiler (https://github.com/vattle/sqlboiler)
// and is meant to be re-generated in place and/or deleted at any time.
// DO NOT EDIT

package sqlboiler

import (
	"bytes"
	"reflect"
	"testing"

	"github.com/vattle/sqlboiler/boil"
	"github.com/vattle/sqlboiler/randomize"
	"github.com/vattle/sqlboiler/strmangle"
)

func testActors(t *testing.T) {
	t.Parallel()

	query := Actors(nil)

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}
func testActorsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	actor := &Actor{}
	if err = randomize.Struct(seed, actor, actorDBTypes, true, actorColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Actor struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = actor.Insert(tx); err != nil {
		t.Error(err)
	}

	if err = actor.Delete(tx); err != nil {
		t.Error(err)
	}

	count, err := Actors(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testActorsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	actor := &Actor{}
	if err = randomize.Struct(seed, actor, actorDBTypes, true, actorColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Actor struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = actor.Insert(tx); err != nil {
		t.Error(err)
	}

	if err = Actors(tx).DeleteAll(); err != nil {
		t.Error(err)
	}

	count, err := Actors(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testActorsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	actor := &Actor{}
	if err = randomize.Struct(seed, actor, actorDBTypes, true, actorColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Actor struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = actor.Insert(tx); err != nil {
		t.Error(err)
	}

	slice := ActorSlice{actor}

	if err = slice.DeleteAll(tx); err != nil {
		t.Error(err)
	}

	count, err := Actors(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}
func testActorsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	actor := &Actor{}
	if err = randomize.Struct(seed, actor, actorDBTypes, true, actorColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Actor struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = actor.Insert(tx); err != nil {
		t.Error(err)
	}

	e, err := ActorExists(tx, actor.ActorID)
	if err != nil {
		t.Errorf("Unable to check if Actor exists: %s", err)
	}
	if !e {
		t.Errorf("Expected ActorExistsG to return true, but got false.")
	}
}
func testActorsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	actor := &Actor{}
	if err = randomize.Struct(seed, actor, actorDBTypes, true, actorColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Actor struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = actor.Insert(tx); err != nil {
		t.Error(err)
	}

	actorFound, err := FindActor(tx, actor.ActorID)
	if err != nil {
		t.Error(err)
	}

	if actorFound == nil {
		t.Error("want a record, got nil")
	}
}
func testActorsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	actor := &Actor{}
	if err = randomize.Struct(seed, actor, actorDBTypes, true, actorColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Actor struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = actor.Insert(tx); err != nil {
		t.Error(err)
	}

	if err = Actors(tx).Bind(actor); err != nil {
		t.Error(err)
	}
}

func testActorsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	actor := &Actor{}
	if err = randomize.Struct(seed, actor, actorDBTypes, true, actorColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Actor struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = actor.Insert(tx); err != nil {
		t.Error(err)
	}

	if x, err := Actors(tx).One(); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testActorsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	actorOne := &Actor{}
	actorTwo := &Actor{}
	if err = randomize.Struct(seed, actorOne, actorDBTypes, false, actorColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Actor struct: %s", err)
	}
	if err = randomize.Struct(seed, actorTwo, actorDBTypes, false, actorColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Actor struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = actorOne.Insert(tx); err != nil {
		t.Error(err)
	}
	if err = actorTwo.Insert(tx); err != nil {
		t.Error(err)
	}

	slice, err := Actors(tx).All()
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testActorsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	actorOne := &Actor{}
	actorTwo := &Actor{}
	if err = randomize.Struct(seed, actorOne, actorDBTypes, false, actorColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Actor struct: %s", err)
	}
	if err = randomize.Struct(seed, actorTwo, actorDBTypes, false, actorColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Actor struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = actorOne.Insert(tx); err != nil {
		t.Error(err)
	}
	if err = actorTwo.Insert(tx); err != nil {
		t.Error(err)
	}

	count, err := Actors(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}
func actorBeforeInsertHook(e boil.Executor, o *Actor) error {
	*o = Actor{}
	return nil
}

func actorAfterInsertHook(e boil.Executor, o *Actor) error {
	*o = Actor{}
	return nil
}

func actorAfterSelectHook(e boil.Executor, o *Actor) error {
	*o = Actor{}
	return nil
}

func actorBeforeUpdateHook(e boil.Executor, o *Actor) error {
	*o = Actor{}
	return nil
}

func actorAfterUpdateHook(e boil.Executor, o *Actor) error {
	*o = Actor{}
	return nil
}

func actorBeforeDeleteHook(e boil.Executor, o *Actor) error {
	*o = Actor{}
	return nil
}

func actorAfterDeleteHook(e boil.Executor, o *Actor) error {
	*o = Actor{}
	return nil
}

func actorBeforeUpsertHook(e boil.Executor, o *Actor) error {
	*o = Actor{}
	return nil
}

func actorAfterUpsertHook(e boil.Executor, o *Actor) error {
	*o = Actor{}
	return nil
}

func testActorsHooks(t *testing.T) {
	t.Parallel()

	var err error

	empty := &Actor{}
	o := &Actor{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, actorDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Actor object: %s", err)
	}

	AddActorHook(boil.BeforeInsertHook, actorBeforeInsertHook)
	if err = o.doBeforeInsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	actorBeforeInsertHooks = []ActorHook{}

	AddActorHook(boil.AfterInsertHook, actorAfterInsertHook)
	if err = o.doAfterInsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	actorAfterInsertHooks = []ActorHook{}

	AddActorHook(boil.AfterSelectHook, actorAfterSelectHook)
	if err = o.doAfterSelectHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	actorAfterSelectHooks = []ActorHook{}

	AddActorHook(boil.BeforeUpdateHook, actorBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	actorBeforeUpdateHooks = []ActorHook{}

	AddActorHook(boil.AfterUpdateHook, actorAfterUpdateHook)
	if err = o.doAfterUpdateHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	actorAfterUpdateHooks = []ActorHook{}

	AddActorHook(boil.BeforeDeleteHook, actorBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	actorBeforeDeleteHooks = []ActorHook{}

	AddActorHook(boil.AfterDeleteHook, actorAfterDeleteHook)
	if err = o.doAfterDeleteHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	actorAfterDeleteHooks = []ActorHook{}

	AddActorHook(boil.BeforeUpsertHook, actorBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	actorBeforeUpsertHooks = []ActorHook{}

	AddActorHook(boil.AfterUpsertHook, actorAfterUpsertHook)
	if err = o.doAfterUpsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	actorAfterUpsertHooks = []ActorHook{}
}
func testActorsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	actor := &Actor{}
	if err = randomize.Struct(seed, actor, actorDBTypes, true, actorColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Actor struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = actor.Insert(tx); err != nil {
		t.Error(err)
	}

	count, err := Actors(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testActorsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	actor := &Actor{}
	if err = randomize.Struct(seed, actor, actorDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Actor struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = actor.Insert(tx, actorColumnsWithoutDefault...); err != nil {
		t.Error(err)
	}

	count, err := Actors(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testActorToManyFilmActors(t *testing.T) {
	var err error
	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var a Actor
	var b, c FilmActor

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, actorDBTypes, true, actorColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Actor struct: %s", err)
	}

	if err := a.Insert(tx); err != nil {
		t.Fatal(err)
	}

	randomize.Struct(seed, &b, filmActorDBTypes, false, filmActorColumnsWithDefault...)
	randomize.Struct(seed, &c, filmActorDBTypes, false, filmActorColumnsWithDefault...)

	b.ActorID = a.ActorID
	c.ActorID = a.ActorID
	if err = b.Insert(tx); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(tx); err != nil {
		t.Fatal(err)
	}

	filmActor, err := a.FilmActors(tx).All()
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range filmActor {
		if v.ActorID == b.ActorID {
			bFound = true
		}
		if v.ActorID == c.ActorID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := ActorSlice{&a}
	if err = a.L.LoadFilmActors(tx, false, (*[]*Actor)(&slice)); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.FilmActors); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.FilmActors = nil
	if err = a.L.LoadFilmActors(tx, true, &a); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.FilmActors); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", filmActor)
	}
}

func testActorToManyAddOpFilmActors(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var a Actor
	var b, c, d, e FilmActor

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, actorDBTypes, false, strmangle.SetComplement(actorPrimaryKeyColumns, actorColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*FilmActor{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, filmActorDBTypes, false, strmangle.SetComplement(filmActorPrimaryKeyColumns, filmActorColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(tx); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(tx); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(tx); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*FilmActor{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddFilmActors(tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ActorID != first.ActorID {
			t.Error("foreign key was wrong value", a.ActorID, first.ActorID)
		}
		if a.ActorID != second.ActorID {
			t.Error("foreign key was wrong value", a.ActorID, second.ActorID)
		}

		if first.R.Actor != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Actor != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.FilmActors[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.FilmActors[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.FilmActors(tx).Count()
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testActorsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	actor := &Actor{}
	if err = randomize.Struct(seed, actor, actorDBTypes, true, actorColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Actor struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = actor.Insert(tx); err != nil {
		t.Error(err)
	}

	if err = actor.Reload(tx); err != nil {
		t.Error(err)
	}
}

func testActorsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	actor := &Actor{}
	if err = randomize.Struct(seed, actor, actorDBTypes, true, actorColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Actor struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = actor.Insert(tx); err != nil {
		t.Error(err)
	}

	slice := ActorSlice{actor}

	if err = slice.ReloadAll(tx); err != nil {
		t.Error(err)
	}
}
func testActorsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	actor := &Actor{}
	if err = randomize.Struct(seed, actor, actorDBTypes, true, actorColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Actor struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = actor.Insert(tx); err != nil {
		t.Error(err)
	}

	slice, err := Actors(tx).All()
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	actorDBTypes = map[string]string{`ActorID`: `smallint`, `FirstName`: `varchar`, `LastName`: `varchar`, `LastUpdate`: `timestamp`}
	_            = bytes.MinRead
)

func testActorsUpdate(t *testing.T) {
	t.Parallel()

	if len(actorColumns) == len(actorPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	actor := &Actor{}
	if err = randomize.Struct(seed, actor, actorDBTypes, true, actorColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Actor struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = actor.Insert(tx); err != nil {
		t.Error(err)
	}

	count, err := Actors(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, actor, actorDBTypes, true, actorColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Actor struct: %s", err)
	}

	if err = actor.Update(tx); err != nil {
		t.Error(err)
	}
}

func testActorsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(actorColumns) == len(actorPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	actor := &Actor{}
	if err = randomize.Struct(seed, actor, actorDBTypes, true, actorColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Actor struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = actor.Insert(tx); err != nil {
		t.Error(err)
	}

	count, err := Actors(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, actor, actorDBTypes, true, actorPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Actor struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(actorColumns, actorPrimaryKeyColumns) {
		fields = actorColumns
	} else {
		fields = strmangle.SetComplement(
			actorColumns,
			actorPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(actor))
	updateMap := M{}
	for _, col := range fields {
		updateMap[col] = value.FieldByName(strmangle.TitleCase(col)).Interface()
	}

	slice := ActorSlice{actor}
	if err = slice.UpdateAll(tx, updateMap); err != nil {
		t.Error(err)
	}
}
func testActorsUpsert(t *testing.T) {
	t.Parallel()

	if len(actorColumns) == len(actorPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	actor := Actor{}
	if err = randomize.Struct(seed, &actor, actorDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Actor struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = actor.Upsert(tx, nil); err != nil {
		t.Errorf("Unable to upsert Actor: %s", err)
	}

	count, err := Actors(tx).Count()
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &actor, actorDBTypes, false, actorPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Actor struct: %s", err)
	}

	if err = actor.Upsert(tx, nil); err != nil {
		t.Errorf("Unable to upsert Actor: %s", err)
	}

	count, err = Actors(tx).Count()
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
