// This file is generated by SQLBoiler (https://github.com/vattle/sqlboiler)
// and is meant to be re-generated in place and/or deleted at any time.
// DO NOT EDIT

package sqlboiler

import (
	"bytes"
	"reflect"
	"testing"

	"github.com/vattle/sqlboiler/boil"
	"github.com/vattle/sqlboiler/randomize"
	"github.com/vattle/sqlboiler/strmangle"
)

func testCountries(t *testing.T) {
	t.Parallel()

	query := Countries(nil)

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}
func testCountriesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	country := &Country{}
	if err = randomize.Struct(seed, country, countryDBTypes, true, countryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Country struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = country.Insert(tx); err != nil {
		t.Error(err)
	}

	if err = country.Delete(tx); err != nil {
		t.Error(err)
	}

	count, err := Countries(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCountriesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	country := &Country{}
	if err = randomize.Struct(seed, country, countryDBTypes, true, countryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Country struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = country.Insert(tx); err != nil {
		t.Error(err)
	}

	if err = Countries(tx).DeleteAll(); err != nil {
		t.Error(err)
	}

	count, err := Countries(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCountriesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	country := &Country{}
	if err = randomize.Struct(seed, country, countryDBTypes, true, countryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Country struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = country.Insert(tx); err != nil {
		t.Error(err)
	}

	slice := CountrySlice{country}

	if err = slice.DeleteAll(tx); err != nil {
		t.Error(err)
	}

	count, err := Countries(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}
func testCountriesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	country := &Country{}
	if err = randomize.Struct(seed, country, countryDBTypes, true, countryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Country struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = country.Insert(tx); err != nil {
		t.Error(err)
	}

	e, err := CountryExists(tx, country.CountryID)
	if err != nil {
		t.Errorf("Unable to check if Country exists: %s", err)
	}
	if !e {
		t.Errorf("Expected CountryExistsG to return true, but got false.")
	}
}
func testCountriesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	country := &Country{}
	if err = randomize.Struct(seed, country, countryDBTypes, true, countryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Country struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = country.Insert(tx); err != nil {
		t.Error(err)
	}

	countryFound, err := FindCountry(tx, country.CountryID)
	if err != nil {
		t.Error(err)
	}

	if countryFound == nil {
		t.Error("want a record, got nil")
	}
}
func testCountriesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	country := &Country{}
	if err = randomize.Struct(seed, country, countryDBTypes, true, countryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Country struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = country.Insert(tx); err != nil {
		t.Error(err)
	}

	if err = Countries(tx).Bind(country); err != nil {
		t.Error(err)
	}
}

func testCountriesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	country := &Country{}
	if err = randomize.Struct(seed, country, countryDBTypes, true, countryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Country struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = country.Insert(tx); err != nil {
		t.Error(err)
	}

	if x, err := Countries(tx).One(); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testCountriesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	countryOne := &Country{}
	countryTwo := &Country{}
	if err = randomize.Struct(seed, countryOne, countryDBTypes, false, countryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Country struct: %s", err)
	}
	if err = randomize.Struct(seed, countryTwo, countryDBTypes, false, countryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Country struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = countryOne.Insert(tx); err != nil {
		t.Error(err)
	}
	if err = countryTwo.Insert(tx); err != nil {
		t.Error(err)
	}

	slice, err := Countries(tx).All()
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testCountriesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	countryOne := &Country{}
	countryTwo := &Country{}
	if err = randomize.Struct(seed, countryOne, countryDBTypes, false, countryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Country struct: %s", err)
	}
	if err = randomize.Struct(seed, countryTwo, countryDBTypes, false, countryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Country struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = countryOne.Insert(tx); err != nil {
		t.Error(err)
	}
	if err = countryTwo.Insert(tx); err != nil {
		t.Error(err)
	}

	count, err := Countries(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}
func countryBeforeInsertHook(e boil.Executor, o *Country) error {
	*o = Country{}
	return nil
}

func countryAfterInsertHook(e boil.Executor, o *Country) error {
	*o = Country{}
	return nil
}

func countryAfterSelectHook(e boil.Executor, o *Country) error {
	*o = Country{}
	return nil
}

func countryBeforeUpdateHook(e boil.Executor, o *Country) error {
	*o = Country{}
	return nil
}

func countryAfterUpdateHook(e boil.Executor, o *Country) error {
	*o = Country{}
	return nil
}

func countryBeforeDeleteHook(e boil.Executor, o *Country) error {
	*o = Country{}
	return nil
}

func countryAfterDeleteHook(e boil.Executor, o *Country) error {
	*o = Country{}
	return nil
}

func countryBeforeUpsertHook(e boil.Executor, o *Country) error {
	*o = Country{}
	return nil
}

func countryAfterUpsertHook(e boil.Executor, o *Country) error {
	*o = Country{}
	return nil
}

func testCountriesHooks(t *testing.T) {
	t.Parallel()

	var err error

	empty := &Country{}
	o := &Country{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, countryDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Country object: %s", err)
	}

	AddCountryHook(boil.BeforeInsertHook, countryBeforeInsertHook)
	if err = o.doBeforeInsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	countryBeforeInsertHooks = []CountryHook{}

	AddCountryHook(boil.AfterInsertHook, countryAfterInsertHook)
	if err = o.doAfterInsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	countryAfterInsertHooks = []CountryHook{}

	AddCountryHook(boil.AfterSelectHook, countryAfterSelectHook)
	if err = o.doAfterSelectHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	countryAfterSelectHooks = []CountryHook{}

	AddCountryHook(boil.BeforeUpdateHook, countryBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	countryBeforeUpdateHooks = []CountryHook{}

	AddCountryHook(boil.AfterUpdateHook, countryAfterUpdateHook)
	if err = o.doAfterUpdateHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	countryAfterUpdateHooks = []CountryHook{}

	AddCountryHook(boil.BeforeDeleteHook, countryBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	countryBeforeDeleteHooks = []CountryHook{}

	AddCountryHook(boil.AfterDeleteHook, countryAfterDeleteHook)
	if err = o.doAfterDeleteHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	countryAfterDeleteHooks = []CountryHook{}

	AddCountryHook(boil.BeforeUpsertHook, countryBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	countryBeforeUpsertHooks = []CountryHook{}

	AddCountryHook(boil.AfterUpsertHook, countryAfterUpsertHook)
	if err = o.doAfterUpsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	countryAfterUpsertHooks = []CountryHook{}
}
func testCountriesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	country := &Country{}
	if err = randomize.Struct(seed, country, countryDBTypes, true, countryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Country struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = country.Insert(tx); err != nil {
		t.Error(err)
	}

	count, err := Countries(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testCountriesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	country := &Country{}
	if err = randomize.Struct(seed, country, countryDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Country struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = country.Insert(tx, countryColumnsWithoutDefault...); err != nil {
		t.Error(err)
	}

	count, err := Countries(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testCountryToManyCities(t *testing.T) {
	var err error
	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var a Country
	var b, c City

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, countryDBTypes, true, countryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Country struct: %s", err)
	}

	if err := a.Insert(tx); err != nil {
		t.Fatal(err)
	}

	randomize.Struct(seed, &b, cityDBTypes, false, cityColumnsWithDefault...)
	randomize.Struct(seed, &c, cityDBTypes, false, cityColumnsWithDefault...)

	b.CountryID = a.CountryID
	c.CountryID = a.CountryID
	if err = b.Insert(tx); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(tx); err != nil {
		t.Fatal(err)
	}

	city, err := a.Cities(tx).All()
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range city {
		if v.CountryID == b.CountryID {
			bFound = true
		}
		if v.CountryID == c.CountryID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := CountrySlice{&a}
	if err = a.L.LoadCities(tx, false, (*[]*Country)(&slice)); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Cities); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.Cities = nil
	if err = a.L.LoadCities(tx, true, &a); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Cities); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", city)
	}
}

func testCountryToManyAddOpCities(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var a Country
	var b, c, d, e City

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, countryDBTypes, false, strmangle.SetComplement(countryPrimaryKeyColumns, countryColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*City{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, cityDBTypes, false, strmangle.SetComplement(cityPrimaryKeyColumns, cityColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(tx); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(tx); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(tx); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*City{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddCities(tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.CountryID != first.CountryID {
			t.Error("foreign key was wrong value", a.CountryID, first.CountryID)
		}
		if a.CountryID != second.CountryID {
			t.Error("foreign key was wrong value", a.CountryID, second.CountryID)
		}

		if first.R.Country != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Country != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.Cities[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.Cities[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.Cities(tx).Count()
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testCountriesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	country := &Country{}
	if err = randomize.Struct(seed, country, countryDBTypes, true, countryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Country struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = country.Insert(tx); err != nil {
		t.Error(err)
	}

	if err = country.Reload(tx); err != nil {
		t.Error(err)
	}
}

func testCountriesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	country := &Country{}
	if err = randomize.Struct(seed, country, countryDBTypes, true, countryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Country struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = country.Insert(tx); err != nil {
		t.Error(err)
	}

	slice := CountrySlice{country}

	if err = slice.ReloadAll(tx); err != nil {
		t.Error(err)
	}
}
func testCountriesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	country := &Country{}
	if err = randomize.Struct(seed, country, countryDBTypes, true, countryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Country struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = country.Insert(tx); err != nil {
		t.Error(err)
	}

	slice, err := Countries(tx).All()
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	countryDBTypes = map[string]string{`Country`: `varchar`, `CountryID`: `smallint`, `LastUpdate`: `timestamp`}
	_              = bytes.MinRead
)

func testCountriesUpdate(t *testing.T) {
	t.Parallel()

	if len(countryColumns) == len(countryPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	country := &Country{}
	if err = randomize.Struct(seed, country, countryDBTypes, true, countryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Country struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = country.Insert(tx); err != nil {
		t.Error(err)
	}

	count, err := Countries(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, country, countryDBTypes, true, countryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Country struct: %s", err)
	}

	if err = country.Update(tx); err != nil {
		t.Error(err)
	}
}

func testCountriesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(countryColumns) == len(countryPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	country := &Country{}
	if err = randomize.Struct(seed, country, countryDBTypes, true, countryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Country struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = country.Insert(tx); err != nil {
		t.Error(err)
	}

	count, err := Countries(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, country, countryDBTypes, true, countryPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Country struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(countryColumns, countryPrimaryKeyColumns) {
		fields = countryColumns
	} else {
		fields = strmangle.SetComplement(
			countryColumns,
			countryPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(country))
	updateMap := M{}
	for _, col := range fields {
		updateMap[col] = value.FieldByName(strmangle.TitleCase(col)).Interface()
	}

	slice := CountrySlice{country}
	if err = slice.UpdateAll(tx, updateMap); err != nil {
		t.Error(err)
	}
}
func testCountriesUpsert(t *testing.T) {
	t.Parallel()

	if len(countryColumns) == len(countryPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	country := Country{}
	if err = randomize.Struct(seed, &country, countryDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Country struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = country.Upsert(tx, nil); err != nil {
		t.Errorf("Unable to upsert Country: %s", err)
	}

	count, err := Countries(tx).Count()
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &country, countryDBTypes, false, countryPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Country struct: %s", err)
	}

	if err = country.Upsert(tx, nil); err != nil {
		t.Errorf("Unable to upsert Country: %s", err)
	}

	count, err = Countries(tx).Count()
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
