// This file is generated by SQLBoiler (https://github.com/vattle/sqlboiler)
// and is meant to be re-generated in place and/or deleted at any time.
// DO NOT EDIT

package sqlboiler

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/vattle/sqlboiler/boil"
	"github.com/vattle/sqlboiler/queries"
	"github.com/vattle/sqlboiler/queries/qm"
	"github.com/vattle/sqlboiler/strmangle"
	"gopkg.in/nullbio/null.v6"
)

// FilmText is an object representing the database table.
type FilmText struct {
	FilmID      int16       `boil:"film_id" json:"film_id" toml:"film_id" yaml:"film_id"`
	Title       string      `boil:"title" json:"title" toml:"title" yaml:"title"`
	Description null.String `boil:"description" json:"description,omitempty" toml:"description" yaml:"description,omitempty"`

	R *filmTextR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L filmTextL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var FilmTextColumns = struct {
	FilmID      string
	Title       string
	Description string
}{
	FilmID:      "film_id",
	Title:       "title",
	Description: "description",
}

// filmTextR is where relationships are stored.
type filmTextR struct {
}

// filmTextL is where Load methods for each relationship are stored.
type filmTextL struct{}

var (
	filmTextColumns               = []string{"film_id", "title", "description"}
	filmTextColumnsWithoutDefault = []string{"film_id", "title", "description"}
	filmTextColumnsWithDefault    = []string{}
	filmTextPrimaryKeyColumns     = []string{"film_id"}
)

type (
	// FilmTextSlice is an alias for a slice of pointers to FilmText.
	// This should generally be used opposed to []FilmText.
	FilmTextSlice []*FilmText
	// FilmTextHook is the signature for custom FilmText hook methods
	FilmTextHook func(boil.Executor, *FilmText) error

	filmTextQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	filmTextType                 = reflect.TypeOf(&FilmText{})
	filmTextMapping              = queries.MakeStructMapping(filmTextType)
	filmTextPrimaryKeyMapping, _ = queries.BindMapping(filmTextType, filmTextMapping, filmTextPrimaryKeyColumns)
	filmTextInsertCacheMut       sync.RWMutex
	filmTextInsertCache          = make(map[string]insertCache)
	filmTextUpdateCacheMut       sync.RWMutex
	filmTextUpdateCache          = make(map[string]updateCache)
	filmTextUpsertCacheMut       sync.RWMutex
	filmTextUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)
var filmTextBeforeInsertHooks []FilmTextHook
var filmTextBeforeUpdateHooks []FilmTextHook
var filmTextBeforeDeleteHooks []FilmTextHook
var filmTextBeforeUpsertHooks []FilmTextHook

var filmTextAfterInsertHooks []FilmTextHook
var filmTextAfterSelectHooks []FilmTextHook
var filmTextAfterUpdateHooks []FilmTextHook
var filmTextAfterDeleteHooks []FilmTextHook
var filmTextAfterUpsertHooks []FilmTextHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *FilmText) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range filmTextBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *FilmText) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range filmTextBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *FilmText) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range filmTextBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *FilmText) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range filmTextBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *FilmText) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range filmTextAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *FilmText) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range filmTextAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *FilmText) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range filmTextAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *FilmText) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range filmTextAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *FilmText) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range filmTextAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddFilmTextHook registers your hook function for all future operations.
func AddFilmTextHook(hookPoint boil.HookPoint, filmTextHook FilmTextHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		filmTextBeforeInsertHooks = append(filmTextBeforeInsertHooks, filmTextHook)
	case boil.BeforeUpdateHook:
		filmTextBeforeUpdateHooks = append(filmTextBeforeUpdateHooks, filmTextHook)
	case boil.BeforeDeleteHook:
		filmTextBeforeDeleteHooks = append(filmTextBeforeDeleteHooks, filmTextHook)
	case boil.BeforeUpsertHook:
		filmTextBeforeUpsertHooks = append(filmTextBeforeUpsertHooks, filmTextHook)
	case boil.AfterInsertHook:
		filmTextAfterInsertHooks = append(filmTextAfterInsertHooks, filmTextHook)
	case boil.AfterSelectHook:
		filmTextAfterSelectHooks = append(filmTextAfterSelectHooks, filmTextHook)
	case boil.AfterUpdateHook:
		filmTextAfterUpdateHooks = append(filmTextAfterUpdateHooks, filmTextHook)
	case boil.AfterDeleteHook:
		filmTextAfterDeleteHooks = append(filmTextAfterDeleteHooks, filmTextHook)
	case boil.AfterUpsertHook:
		filmTextAfterUpsertHooks = append(filmTextAfterUpsertHooks, filmTextHook)
	}
}

// OneP returns a single filmText record from the query, and panics on error.
func (q filmTextQuery) OneP() *FilmText {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single filmText record from the query.
func (q filmTextQuery) One() (*FilmText, error) {
	o := &FilmText{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: failed to execute a one query for film_text")
	}

	if err := o.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
		return o, err
	}

	return o, nil
}

// AllP returns all FilmText records from the query, and panics on error.
func (q filmTextQuery) AllP() FilmTextSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all FilmText records from the query.
func (q filmTextQuery) All() (FilmTextSlice, error) {
	var o []*FilmText

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "sqlboiler: failed to assign all query results to FilmText slice")
	}

	if len(filmTextAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountP returns the count of all FilmText records in the query, and panics on error.
func (q filmTextQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all FilmText records in the query.
func (q filmTextQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to count film_text rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q filmTextQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q filmTextQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: failed to check if film_text exists")
	}

	return count > 0, nil
}

// FilmTextsG retrieves all records.
func FilmTextsG(mods ...qm.QueryMod) filmTextQuery {
	return FilmTexts(boil.GetDB(), mods...)
}

// FilmTexts retrieves all the records using an executor.
func FilmTexts(exec boil.Executor, mods ...qm.QueryMod) filmTextQuery {
	mods = append(mods, qm.From("`film_text`"))
	return filmTextQuery{NewQuery(exec, mods...)}
}

// FindFilmTextG retrieves a single record by ID.
func FindFilmTextG(filmID int16, selectCols ...string) (*FilmText, error) {
	return FindFilmText(boil.GetDB(), filmID, selectCols...)
}

// FindFilmTextGP retrieves a single record by ID, and panics on error.
func FindFilmTextGP(filmID int16, selectCols ...string) *FilmText {
	retobj, err := FindFilmText(boil.GetDB(), filmID, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindFilmText retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindFilmText(exec boil.Executor, filmID int16, selectCols ...string) (*FilmText, error) {
	filmTextObj := &FilmText{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `film_text` where `film_id`=?", sel,
	)

	q := queries.Raw(exec, query, filmID)

	err := q.Bind(filmTextObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: unable to select from film_text")
	}

	return filmTextObj, nil
}

// FindFilmTextP retrieves a single record by ID with an executor, and panics on error.
func FindFilmTextP(exec boil.Executor, filmID int16, selectCols ...string) *FilmText {
	retobj, err := FindFilmText(exec, filmID, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *FilmText) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *FilmText) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *FilmText) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *FilmText) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("sqlboiler: no film_text provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(filmTextColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	filmTextInsertCacheMut.RLock()
	cache, cached := filmTextInsertCache[key]
	filmTextInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			filmTextColumns,
			filmTextColumnsWithDefault,
			filmTextColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(filmTextType, filmTextMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(filmTextType, filmTextMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `film_text` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `film_text` () VALUES ()"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `film_text` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, filmTextPrimaryKeyColumns))
		}

		if len(wl) != 0 {
			cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	_, err = exec.Exec(cache.query, vals...)
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to insert into film_text")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.FilmID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to populate default values for film_text")
	}

CacheNoHooks:
	if !cached {
		filmTextInsertCacheMut.Lock()
		filmTextInsertCache[key] = cache
		filmTextInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single FilmText record. See Update for
// whitelist behavior description.
func (o *FilmText) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single FilmText record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *FilmText) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the FilmText, and panics on error.
// See Update for whitelist behavior description.
func (o *FilmText) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the FilmText.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *FilmText) Update(exec boil.Executor, whitelist ...string) error {
	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return err
	}
	key := makeCacheKey(whitelist, nil)
	filmTextUpdateCacheMut.RLock()
	cache, cached := filmTextUpdateCache[key]
	filmTextUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(
			filmTextColumns,
			filmTextPrimaryKeyColumns,
			whitelist,
		)

		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("sqlboiler: unable to update film_text, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `film_text` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, filmTextPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(filmTextType, filmTextMapping, append(wl, filmTextPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to update film_text row")
	}

	if !cached {
		filmTextUpdateCacheMut.Lock()
		filmTextUpdateCache[key] = cache
		filmTextUpdateCacheMut.Unlock()
	}

	return o.doAfterUpdateHooks(exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q filmTextQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q filmTextQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to update all for film_text")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o FilmTextSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o FilmTextSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o FilmTextSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o FilmTextSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("sqlboiler: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), filmTextPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `film_text` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, filmTextPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to update all in filmText slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *FilmText) UpsertG(updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *FilmText) UpsertGP(updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *FilmText) UpsertP(exec boil.Executor, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *FilmText) Upsert(exec boil.Executor, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("sqlboiler: no film_text provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(filmTextColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	filmTextUpsertCacheMut.RLock()
	cache, cached := filmTextUpsertCache[key]
	filmTextUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := strmangle.InsertColumnSet(
			filmTextColumns,
			filmTextColumnsWithDefault,
			filmTextColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		update := strmangle.UpdateColumnSet(
			filmTextColumns,
			filmTextPrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("sqlboiler: unable to upsert film_text, could not build update column list")
		}

		cache.query = queries.BuildUpsertQueryMySQL(dialect, "film_text", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `film_text` WHERE `film_id`=?",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
		)

		cache.valueMapping, err = queries.BindMapping(filmTextType, filmTextMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(filmTextType, filmTextMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	_, err = exec.Exec(cache.query, vals...)
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to upsert for film_text")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.FilmID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to populate default values for film_text")
	}

CacheNoHooks:
	if !cached {
		filmTextUpsertCacheMut.Lock()
		filmTextUpsertCache[key] = cache
		filmTextUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteP deletes a single FilmText record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *FilmText) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single FilmText record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *FilmText) DeleteG() error {
	if o == nil {
		return errors.New("sqlboiler: no FilmText provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single FilmText record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *FilmText) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single FilmText record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *FilmText) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("sqlboiler: no FilmText provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), filmTextPrimaryKeyMapping)
	sql := "DELETE FROM `film_text` WHERE `film_id`=?"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to delete from film_text")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return err
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q filmTextQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q filmTextQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("sqlboiler: no filmTextQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to delete all from film_text")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o FilmTextSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o FilmTextSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("sqlboiler: no FilmText slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o FilmTextSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o FilmTextSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("sqlboiler: no FilmText slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	if len(filmTextBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), filmTextPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `film_text` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, filmTextPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to delete all from filmText slice")
	}

	if len(filmTextAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *FilmText) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *FilmText) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *FilmText) ReloadG() error {
	if o == nil {
		return errors.New("sqlboiler: no FilmText provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *FilmText) Reload(exec boil.Executor) error {
	ret, err := FindFilmText(exec, o.FilmID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *FilmTextSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *FilmTextSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *FilmTextSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("sqlboiler: empty FilmTextSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *FilmTextSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	filmTexts := FilmTextSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), filmTextPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `film_text`.* FROM `film_text` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, filmTextPrimaryKeyColumns, len(*o))

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&filmTexts)
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to reload all in FilmTextSlice")
	}

	*o = filmTexts

	return nil
}

// FilmTextExists checks if the FilmText row exists.
func FilmTextExists(exec boil.Executor, filmID int16) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `film_text` where `film_id`=? limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, filmID)
	}

	row := exec.QueryRow(sql, filmID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: unable to check if film_text exists")
	}

	return exists, nil
}

// FilmTextExistsG checks if the FilmText row exists.
func FilmTextExistsG(filmID int16) (bool, error) {
	return FilmTextExists(boil.GetDB(), filmID)
}

// FilmTextExistsGP checks if the FilmText row exists. Panics on error.
func FilmTextExistsGP(filmID int16) bool {
	e, err := FilmTextExists(boil.GetDB(), filmID)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// FilmTextExistsP checks if the FilmText row exists. Panics on error.
func FilmTextExistsP(exec boil.Executor, filmID int16) bool {
	e, err := FilmTextExists(exec, filmID)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
